repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: compileall
        name: compileall
        entry: python3 -B -m compileall -q ies_bot_skeleton tests adapters.py adaptive.py constants.py controllers_balance.py controllers_solar.py controllers_wear.py forecasts.py ies.py main.py models.py state.py utils.py
        language: system
        pass_filenames: false
