"""initial web schema

Revision ID: b266c1d655ae
Revises:
Create Date: 2026-03-10 20:55:26.423610

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b266c1d655ae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "object_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("subtype", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("default_parameters_json", sa.JSON(), nullable=False),
        sa.Column("editable_fields_json", sa.JSON(), nullable=False),
        sa.Column("rules_json", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "rulesets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "version", name="uq_ruleset_code_version"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "game_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("ruleset_id", sa.Integer(), nullable=False),
        sa.Column("selected_strategy", sa.String(length=64), nullable=False),
        sa.Column("budget_total", sa.Float(), nullable=False),
        sa.Column("allpay_spent", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ruleset_id"],
            ["rulesets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forecasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_file", sa.String(length=255), nullable=False),
        sa.Column("column_map_json", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("base_bid", sa.Float(), nullable=False),
        sa.Column("current_bid", sa.Float(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("available_round", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lots", schema=None) as batch_op:
        batch_op.create_index("ix_lot_session_status", ["session_id", "status"], unique=False)

    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("lot_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("scenario", sa.String(length=32), nullable=False),
        sa.Column("summary_score", sa.Float(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("recommended_bid_soft", sa.Float(), nullable=False),
        sa.Column("recommended_bid_hard", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["lots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evaluation_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_eval_session_lot_mode_created_desc",
            ["session_id", "lot_id", "mode", sa.literal_column("created_at DESC")],
            unique=False,
        )

    op.create_table(
        "forecast_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("forecast_id", sa.Integer(), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.Column("illumination", sa.Float(), nullable=True),
        sa.Column("wind", sa.Float(), nullable=True),
        sa.Column("market_price", sa.Float(), nullable=True),
        sa.Column("consumption_json", sa.JSON(), nullable=False),
        sa.Column("extra_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_id"],
            ["forecasts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("forecast_id", "tick", name="uq_forecast_period_tick"),
    )
    with op.batch_alter_table("forecast_periods", schema=None) as batch_op:
        batch_op.create_index(
            "ix_forecast_period_forecast_tick", ["forecast_id", "tick"], unique=False
        )

    op.create_table(
        "lot_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lot_id", sa.Integer(), nullable=False),
        sa.Column("object_type_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("overrides_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["lots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["object_type_id"],
            ["object_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "object_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("object_type_id", sa.Integer(), nullable=False),
        sa.Column("custom_name", sa.String(length=128), nullable=False),
        sa.Column("current_parameters_json", sa.JSON(), nullable=False),
        sa.Column("source_lot_id", sa.Integer(), nullable=True),
        sa.Column("is_from_start_pack", sa.Boolean(), nullable=False),
        sa.Column("parent_instance_id", sa.Integer(), nullable=True),
        sa.Column("district", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_type_id"],
            ["object_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_instance_id"],
            ["object_instances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["game_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_lot_id"],
            ["lots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("object_instances", schema=None) as batch_op:
        batch_op.create_index(
            "ix_object_instance_session_object_type", ["session_id", "object_type_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("object_instances", schema=None) as batch_op:
        batch_op.drop_index("ix_object_instance_session_object_type")

    op.drop_table("object_instances")
    op.drop_table("lot_items")
    with op.batch_alter_table("forecast_periods", schema=None) as batch_op:
        batch_op.drop_index("ix_forecast_period_forecast_tick")

    op.drop_table("forecast_periods")
    with op.batch_alter_table("evaluation_results", schema=None) as batch_op:
        batch_op.drop_index("ix_eval_session_lot_mode_created_desc")

    op.drop_table("evaluation_results")
    with op.batch_alter_table("lots", schema=None) as batch_op:
        batch_op.drop_index("ix_lot_session_status")

    op.drop_table("lots")
    op.drop_table("forecasts")
    op.drop_table("game_sessions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    op.drop_table("rulesets")
    op.drop_table("object_types")
    # ### end Alembic commands ###
